# Generated by Django 2.0.13 on 2019-07-01 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festflow', '0004_college_volunteerlogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='volunteerlogin',
        ),
    ]
