# Generated by Django 2.0.13 on 2019-07-01 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festflow', '0005_delete_volunteerlogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='institute_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festflow.College'),
        ),
    ]
