# Generated by Django 2.0.13 on 2019-07-02 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festflow', '0006_auto_20190701_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='institute_name',
            field=models.CharField(max_length=255),
        ),
    ]
